# to make script an executable: run 'chmod +x launch_ini_files.sh', then execute using 'bash script.sh' 
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio100_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio100_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio100_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio100_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio100_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio100_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio85_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio85_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio85_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio85_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio85_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio85_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio65_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio65_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio65_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio65_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio65_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio65_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio50_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio50_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio50_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio50_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio50_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/H4_massratio50_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio100_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio100_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio100_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio100_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio100_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio100_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio85_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio85_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio85_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio85_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio85_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio85_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio65_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio65_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio65_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio65_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio65_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio65_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio50_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio50_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio50_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio50_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio50_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/MS1_massratio50_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio100_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio100_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio100_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio100_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio100_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio100_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio85_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio85_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio85_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio85_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio85_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio85_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio65_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio65_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio65_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio65_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio65_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio65_SNR30_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio50_SNR15_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio50_SNR15_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio50_SNR15_common_radius.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio50_SNR30_l1l2.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio50_SNR30_binary_love.ini --submit
bilby_pipe /home/kyle.wong/ini_files_to_recreate_plots/WFF1_massratio50_SNR30_common_radius.ini --submit
